name: 'trx-tools.Reporting'
description: 'Generate reports from multiple trx files'
author: BrammyS
branding:
  icon: bar-chart
  color: blue
  
inputs:
  report-type:
    description: 'Type of report to generate'
    required: false
    default: 'html'
  trx-directory:
    description: 'Directory containing trx files'
    required: false
    default: './'
  report-file:
    description: 'File to write report to'
    required: false
    default: 'report.html'
runs:
  using: 'docker'
  image: 'ghcr.io/brammys/trx-tools.reporting:v1.0.3-beta.3'
  args:
    - ${{ inputs.report-type }} ${{ inputs.trx-directory }} ${{ inputs.report-file }}
